import { NavLink, PricingTier, Testimonial, FaqItem, PortfolioItem, AdSample, TrustBadge, ServiceItem } from '@/types';

export const BRAND = {
  name: 'NABS Marketing',
  tagline: 'Where Ads Meet Revenue',
  headline: 'We Turn Your Facebook & Instagram Ads Into Real Customers.',
  subHeadline: 'High-converting ad campaigns tailored for Restaurants & Clothing Brands in Bangladesh. Data-driven targeting, lower cost per lead, and transparent ROI reporting.',
  whatsappNumber: '8801616696502',
  whatsappUrl: 'https://wa.me/8801616696502?text=Hi%20NABS%20Marketing%2C%20I%20want%20to%20get%20a%20free%20consultation%20for%20my%20business.',
  email: 'nabsmarketingagency@gmail.com',
  phone: '+880 1616-696502',
  instagram: '@nabs_ads',
  instagramUrl: 'https://instagram.com/nabs_ads',
  businessHours: 'Saturday – Thursday: 9:00 AM – 9:00 PM (Bangladesh Time)',
  founderName: 'Sojib',
  founderRole: 'Founder & Lead Performance Marketer',
};

export const NAV_LINKS: NavLink[] = [
  { title: 'Home', href: '/' },
  { title: 'Services', href: '/services' },
  { title: 'Portfolio', href: '/portfolio' },
  { title: 'About', href: '/about' },
  { title: 'Contact', href: '/contact' },
];

export const TRUST_STATS = [
  { value: '15+', label: 'Campaigns Managed' },
  { value: '15,000+', label: 'People Reached' },
  { value: '100%', label: 'Client Satisfaction' },
];

export const TRUST_BADGES: TrustBadge[] = [
  {
    id: 'badge-1',
    title: 'Meta Certified Knowledge',
    description: 'Up-to-date Meta Ads policies & algorithms',
    iconName: 'ShieldCheck',
  },
  {
    id: 'badge-2',
    title: 'No Hidden Fees',
    description: '100% transparent pricing structure',
    iconName: 'BadgeCheck',
  },
  {
    id: 'badge-3',
    title: 'Results in 7 Days',
    description: 'Quick campaign setup & early traction',
    iconName: 'Clock',
  },
  {
    id: 'badge-4',
    title: 'Bangladesh Specialists',
    description: 'Deep understanding of local audience buying behavior',
    iconName: 'MapPin',
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'facebook-ads',
    title: 'Facebook Ads Management',
    description: 'End-to-end Facebook ad campaigns built to drive high-intent foot traffic for restaurants and online sales for fashion brands across Bangladesh.',
    features: [
      'Custom audience creation & pixel integration',
      'High-converting ad copy & carousel/video creatives',
      'A/B testing for ad placements & copy',
      'Daily performance tracking & budget reallocation',
      'Weekly transparent analytics report',
      'Dedicated ad manager support',
    ],
    iconName: 'Megaphone',
    badge: 'Core Service',
  },
  {
    id: 'instagram-ads',
    title: 'Instagram Ads Management',
    description: 'Visual story ads, Reels promotions, and shoppable post ads engineered to capture young demographic attention and scale order volume.',
    features: [
      'Reels & Story ad creative optimization',
      'Influencer-style UGC ad formatting',
      'Direct message (DM) automation setup',
      'Audience demographic refinement',
      'Retargeting website visitors & engagers',
      'Brand aesthetic consistency check',
    ],
    iconName: 'Instagram',
    badge: 'Popular',
  },
  {
    id: 'lead-generation',
    title: 'Lead Generation Campaigns',
    description: 'Instant lead forms and Messenger/WhatsApp conversion campaigns that convert curious browsers into paid table bookings and direct orders.',
    features: [
      'Custom Meta Lead Form configuration',
      'Instant Messenger & WhatsApp chat routing',
      'Offer creation (Discounts, Bundles, VIP passes)',
      'Lead qualification filter questions',
      'CRM/Google Sheet instant sync',
      'Follow-up sequence recommendations',
    ],
    iconName: 'Users',
    badge: 'High ROI',
  },
  {
    id: 'campaign-setup-optimization',
    title: 'Campaign Audit & Optimization',
    description: 'Got existing ads that underperform? We audit your ad account structure, fix pixel tracking errors, and optimize targeting to cut wasted spend.',
    features: [
      'Full account & pixel health audit',
      'Audience overlap diagnosis',
      'Creative fatigue check & refresh schedule',
      'Cost-per-click (CPC) & ROAS optimization',
      'Landing page & conversion path check',
      'Actionable 30-day turnaround strategy',
    ],
    iconName: 'Settings2',
  },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'starter-trial',
    name: 'Starter Trial',
    subtitle: 'Test the Water',
    price: '2,500–3,500৳',
    period: '/ 7 days',
    minAdSpend: '1,500৳',
    description: 'Ideal for trying out paid ads with a low-risk 7-day initial test run.',
    features: [
      '1 Meta Ad Campaign',
      '1 High-converting Ad Creative',
      'Facebook or Instagram placement',
      'Basic performance report',
    ],
    ctaText: 'Start 7-Day Trial',
    ctaHref: '/contact?package=starter-trial',
  },
  {
    id: 'growth-month',
    name: 'Growth Month',
    subtitle: 'Build Momentum',
    price: '6,000–8,000৳',
    period: '/ 30 days',
    minAdSpend: '6,000৳',
    description: 'Our most popular plan to build consistent lead flow and revenue momentum.',
    isPopular: true,
    features: [
      '2 Active Ad Campaigns',
      '3-4 High-converting Ad Creatives',
      'Facebook + Instagram placements',
      'A/B Creative & Placement testing',
      'Weekly detailed performance reports',
    ],
    ctaText: 'Claim Growth Plan',
    ctaHref: '/contact?package=growth-month',
  },
  {
    id: 'full-scale',
    name: 'Full Scale',
    subtitle: 'Dominate Your Market',
    price: '12,000–15,000৳',
    period: '/ 30 days',
    minAdSpend: '12,000৳',
    description: 'Aggressive multi-campaign scaling for maximum market dominance & high volume ROI.',
    features: [
      '4 Scaling Ad Campaigns',
      '6-8 High-converting Ad Creatives',
      'Advanced audience geotargeting',
      'Daily monitoring & budget scaling',
    ],
    ctaText: 'Scale Your Brand',
    ctaHref: '/contact?package=full-scale',
  },
  {
    id: 'custom',
    name: 'Custom',
    subtitle: 'Build Your Own',
    price: 'Custom Quote',
    period: 'Flexible duration',
    minAdSpend: 'Varies',
    description: 'Fully customized strategy tailored specifically to your business goals and scale.',
    features: [
      'Tailored to specific client needs',
      'Custom campaign structure & volume',
      'Flexible duration & budget rules',
      'Dedicated strategy consultation',
    ],
    ctaText: 'Get Custom Quote',
    ctaHref: '/contact?package=custom',
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'How much should I spend on Meta ad budget?',
    answer: 'Your ad spend is paid directly to Meta (Facebook/Instagram). For local Bangladeshi businesses, we recommend starting with at least 5,000৳ to 15,000৳ per month for ad spend, separate from our management fee. We optimize every Taka for maximum ROI.',
  },
  {
    id: 'faq-2',
    question: 'How quickly will I see results from my campaigns?',
    answer: 'Initial campaign setup takes 2–3 days. Most clients start receiving qualified leads, messages, or restaurant inquiries within 48 to 72 hours of campaign activation. Full audience optimization matures by day 7 to 14.',
  },
  {
    id: 'faq-3',
    question: 'Do I need an existing Facebook Page or Instagram Business Account?',
    answer: 'Yes, but if you do not have one or yours needs professional tuning, our team will guide you through setting up or optimizing your Business Manager, Ad Account, and Facebook Page as part of onboarding.',
  },
  {
    id: 'faq-4',
    question: 'What if my current ads are already underperforming?',
    answer: 'We begin with a comprehensive account audit to identify why your current ads fail—whether it is improper audience targeting, weak creative, or high cost-per-click—and rebuild your campaigns using proven Bangladeshi market funnels.',
  },
  {
    id: 'faq-5',
    question: 'What payment methods do you accept for agency fees and Meta ad spend?',
    answer: 'For our management packages, we accept bKash, Nagad, Rocket, and Direct Bank Transfer. For Meta ad spend, you pay Meta directly using a dual-currency credit/debit card (EBL Aqua, City Bank, etc.) or we can advise you on compliant payment setups.',
  },
  {
    id: 'faq-6',
    question: 'Is there a long-term contract requirement?',
    answer: 'No long-term lock-in contracts! Our management plans operate on a month-to-month basis. We earn your business every single month through measurable revenue growth and transparent reporting.',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    quote: 'NABS Marketing scaled our weekend table reservations by over 140% within just 3 weeks of launching targeted Instagram Reels ads. Their understanding of local food lovers in Dhaka is unmatched.',
    clientName: 'Tanvir Ahmed',
    businessName: 'Spicy Dine Restaurant (Dhaka)',
    rating: 5,
    niche: 'restaurant',
  },
  {
    id: 'test-2',
    quote: 'Our new Eid panjabi collection sold out 10 days earlier than expected. NABS set up messenger automation that converted direct queries into confirmed sales seamlessly.',
    clientName: 'Nadia Rahman',
    businessName: 'Vogue Craft Apparel',
    rating: 5,
    niche: 'clothing',
  },
  {
    id: 'test-3',
    quote: 'Extremely transparent reporting and zero BS. They lowered our Cost-Per-Lead from 45৳ down to 18৳, allowing us to double our monthly ad budget with confidence.',
    clientName: 'Rafiqul Islam',
    businessName: 'Urban Bites & Cafe',
    rating: 5,
    niche: 'restaurant',
  },
];

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 'port-1',
    title: "Loom & Co. — Men's New Collection Launch",
    category: 'clothing',
    categoryLabel: 'Clothing & Fashion',
    reach: '15,400+ Reached',
    leadsOrSales: '180+ Direct Orders',
    adSpend: '6,500৳ Ad Budget',
    description: "High-converting Meta ad creative campaign promoting Loom & Co.'s latest Men's Fashion collection across Bangladesh.",
    isSampleData: false,
    image: '/portfolio/loom-new-collection.jpg',
  },
  {
    id: 'port-2',
    title: 'Loom & Co. — Gentle Lifestyle Outerwear',
    category: 'clothing',
    categoryLabel: 'Clothing & Fashion',
    reach: '18,200+ Reached',
    leadsOrSales: '210+ Messenger Inquiries',
    adSpend: '7,200৳ Ad Budget',
    description: 'Premium brown suede jacket campaign engineered to capture high-intent fashion enthusiasts with 3.8x ROAS.',
    isSampleData: false,
    image: '/portfolio/loom-gentle-lifestyle.jpg',
  },
  {
    id: 'port-3',
    title: 'Loom & Co. — Find Your Signature Style',
    category: 'clothing',
    categoryLabel: 'Clothing & Fashion',
    reach: '12,800+ Reached',
    leadsOrSales: '145+ Direct Orders',
    adSpend: '5,000৳ Ad Budget',
    description: 'Trendsetter denim and casualwear promo engineered for young adult male demographics in Dhaka.',
    isSampleData: false,
    image: '/portfolio/loom-find-your-style.jpg',
  },
  {
    id: 'port-4',
    title: 'Loom & Co. — Elevate Your Everyday Look',
    category: 'clothing',
    categoryLabel: 'Clothing & Fashion',
    reach: '14,100+ Reached',
    leadsOrSales: '165+ Direct Sales',
    adSpend: '5,800৳ Ad Budget',
    description: 'High-converting portrait ad creative driving immediate WhatsApp checkout orders and brand engagement.',
    isSampleData: false,
    image: '/portfolio/loom-elevate-everyday.jpg',
  },
  {
    id: 'port-5',
    title: 'Dhaka Gourmet Bistro Launch',
    category: 'restaurant',
    categoryLabel: 'Restaurant & Dining',
    reach: '12,500+ Impressions',
    leadsOrSales: '120+ Table Reservations',
    adSpend: '4,500৳ Ad Budget',
    description: 'High-impact geotargeted video ad campaign targeting food enthusiasts within a 5km radius in Gulshan & Banani.',
    isSampleData: true,
  },
];

export const AD_SAMPLES: AdSample[] = [
  {
    id: 'ad-sample-1',
    title: 'Loom & Co. New Collection Ad',
    category: 'clothing',
    aspectRatio: '4:5 Feed Creative',
    tag: 'Fashion Concept',
    gradient: 'from-slate-700/40 to-slate-900/60',
    icon: 'Shirt',
    image: '/portfolio/loom-new-collection.jpg',
  },
  {
    id: 'ad-sample-2',
    title: 'Loom & Co. Elevate Everyday Look',
    category: 'clothing',
    aspectRatio: 'Portrait Ad Creative',
    tag: 'Urban Fashion',
    gradient: 'from-amber-900/40 to-stone-900/60',
    icon: 'Shirt',
    image: '/portfolio/loom-elevate-everyday.jpg',
  },
  {
    id: 'ad-sample-3',
    title: 'Loom & Co. Buy Now Campaign',
    category: 'clothing',
    aspectRatio: 'Square Feed Ad',
    tag: 'Direct Checkout',
    gradient: 'from-blue-900/40 to-slate-900/60',
    icon: 'Shirt',
    image: '/portfolio/loom-buy-now.jpg',
  },
  {
    id: 'ad-sample-4',
    title: 'Loom & Co. Gentle Gentleman Ad',
    category: 'clothing',
    aspectRatio: 'Square Poster Creative',
    tag: 'Premium Suede',
    gradient: 'from-yellow-900/40 to-amber-950/60',
    icon: 'Shirt',
    image: '/portfolio/loom-gentle-lifestyle.jpg',
  },
  {
    id: 'ad-sample-5',
    title: 'Loom & Co. Find Your Style',
    category: 'clothing',
    aspectRatio: 'Portrait Trend Creative',
    tag: 'Men\'s Denim',
    gradient: 'from-sky-900/40 to-slate-900/60',
    icon: 'Shirt',
    image: '/portfolio/loom-find-your-style.jpg',
  },
];
